name: eco_navi_fe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  build_runner: ^2.5.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^2.2.0
  geolocator: ^14.0.2
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  image_picker: ^1.1.2
  kakao_flutter_sdk_common: ^1.9.7+3
  shared_preferences: ^2.3.2
  kakao_flutter_sdk_user: ^1.9.7+3
  pointer_interceptor: ^0.10.1+2
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
 
  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard/Pretendard-Thin.woff
          weight: 100
        - asset: fonts/Pretendard/Pretendard-ExtraLight.woff
          weight: 200
        - asset: fonts/Pretendard/Pretendard-Light.woff
          weight: 300
        - asset: fonts/Pretendard/Pretendard-Regular.woff
          weight: 400
        - asset: fonts/Pretendard/Pretendard-Medium.woff
          weight: 500
        - asset: fonts/Pretendard/Pretendard-SemiBold.woff
          weight: 600
        - asset: fonts/Pretendard/Pretendard-Bold.woff
          weight: 700
        - asset: fonts/Pretendard/Pretendard-ExtraBold.woff
          weight: 800
        - asset: fonts/Pretendard/Pretendard-Black.woff
          weight: 900
  
  assets:
    - .env
    - config/
    - svg/
    - png/